from .at_exchanger import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .at_exchanger__advanced_ import (
    NODE_CLASS_MAPPINGS as ADV_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ADV_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **ADV_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **ADV_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
